/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Se3debWVDOl
 */

import { categories } from "@/app/main/category/data/categories";
import {
  CardTitle,
  CardDescription,
  CardContent,
  Card,
} from "@/components/ui/card";
import Link from "next/link";

export function Category() {
  return (
    <section className="w-full py-6">
      <div className="container grid max-w-4xl gap-4 px-4 md:gap-6 lg:px-6">
        <div className="space-y-2">
          <h2 className="text-3xl font-bold tracking-tighter">
            Explore Categories
          </h2>
        </div>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          {categories.map((category: any) => {
            return (
              <Link key={category.id} href={category.href}>
                <Card className="cursor-pointer hover:scale-105 transition-transform">
                  <CardContent className="flex items-center gap-4 p-4">
                    {category.icon}
                    <div className="flex-1">
                      <CardTitle>{category.name}</CardTitle>
                      <CardDescription>{category.description}</CardDescription>
                    </div>
                    <ChevronRightIcon className="w-4 h-4" />
                  </CardContent>
                </Card>
              </Link>
            );
          })}

          {/* <Card className="cursor-pointer hover:scale-105 transition-transform">
            <CardContent className="flex items-center gap-4 p-4">
              <FrameIcon className="w-6 h-6" />
              <div className="flex-1">
                <CardTitle>Device Frames</CardTitle>
                <CardDescription>
                  Add device frames to your screenshots
                </CardDescription>
              </div>
              <ChevronRightIcon className="w-4 h-4" />
            </CardContent>
          </Card>
          <Card className="cursor-pointer hover:scale-105 transition-transform">
            <CardContent className="flex items-center gap-4 p-4">
              <CodeIcon className="w-6 h-6" />
              <div className="flex-1">
                <CardTitle>Code</CardTitle>
                <CardDescription>
                  Share beautiful and formatted code snippets
                </CardDescription>
              </div>
              <ChevronRightIcon className="w-4 h-4" />
            </CardContent>
          </Card>
          <Card className="cursor-pointer hover:scale-105 transition-transform">
            <CardContent className="flex items-center gap-4 p-4">
              <ChromeIcon className="w-6 h-6" />
              <div className="flex-1">
                <CardTitle>Browser</CardTitle>
                <CardDescription>
                  Embed interactive web browsers in your apps
                </CardDescription>
              </div>
              <ChevronRightIcon className="w-4 h-4" />
            </CardContent>
          </Card> */}
        </div>
      </div>
    </section>
  );
}

function AccessibilityIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="16" cy="4" r="1" />
      <path d="m18 19 1-7-6 1" />
      <path d="m5 8 3-3 5.5 3-2.36 3.5" />
      <path d="M4.24 14.5a5 5 0 0 0 6.88 6" />
      <path d="M13.76 17.5a5 5 0 0 0-6.88-6" />
    </svg>
  );
}

function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  );
}

function FrameIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="22" x2="2" y1="6" y2="6" />
      <line x1="22" x2="2" y1="18" y2="18" />
      <line x1="6" x2="6" y1="2" y2="22" />
      <line x1="18" x2="18" y1="2" y2="22" />
    </svg>
  );
}

function CodeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  );
}

function ChromeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  );
}
