/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Se3debWVDOl
 */

import { categories } from "@/app/main/category/data/categories";
import {
  CardTitle,
  CardDescription,
  CardContent,
  Card,
} from "@/components/ui/card";
import { ChevronRightIcon } from "lucide-react";
import Link from "next/link";

export function Category() {
  return (
    <section className="w-full py-6">
      <div className="container grid max-w-4xl gap-4 px-4 md:gap-6 lg:px-6">
        <div className="space-y-2">
          <h2 className="text-3xl font-bold tracking-tighter">
            Explore Categories
          </h2>
        </div>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          {categories.map((category: any) => {
            return (
              <Link key={category.id} href={category.href}>
                <Card className="cursor-pointer hover:scale-105 transition-transform">
                  <CardContent className="flex items-center gap-4 p-4">
                    {category.icon}
                    <div className="flex-1">
                      <CardTitle>{category.name}</CardTitle>
                      <CardDescription>{category.description}</CardDescription>
                    </div>
                    <ChevronRightIcon className="w-4 h-4" />
                  </CardContent>
                </Card>
              </Link>
            );
          })}

          {/* <Card className="cursor-pointer hover:scale-105 transition-transform">
            <CardContent className="flex items-center gap-4 p-4">
              <FrameIcon className="w-6 h-6" />
              <div className="flex-1">
                <CardTitle>Device Frames</CardTitle>
                <CardDescription>
                  Add device frames to your screenshots
                </CardDescription>
              </div>
              <ChevronRightIcon className="w-4 h-4" />
            </CardContent>
          </Card>
          <Card className="cursor-pointer hover:scale-105 transition-transform">
            <CardContent className="flex items-center gap-4 p-4">
              <CodeIcon className="w-6 h-6" />
              <div className="flex-1">
                <CardTitle>Code</CardTitle>
                <CardDescription>
                  Share beautiful and formatted code snippets
                </CardDescription>
              </div>
              <ChevronRightIcon className="w-4 h-4" />
            </CardContent>
          </Card>
          <Card className="cursor-pointer hover:scale-105 transition-transform">
            <CardContent className="flex items-center gap-4 p-4">
              <ChromeIcon className="w-6 h-6" />
              <div className="flex-1">
                <CardTitle>Browser</CardTitle>
                <CardDescription>
                  Embed interactive web browsers in your apps
                </CardDescription>
              </div>
              <ChevronRightIcon className="w-4 h-4" />
            </CardContent>
          </Card> */}
        </div>
      </div>
    </section>
  );
}
