/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cfjbMssjhaC
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Github } from "lucide-react";

export function LoginBox() {
  return (
    <div className="flex h-screen w-full items-center justify-center bg-gradient-to-br from-slate-100 to-slate-500">
      <Card className="mx-auto max-w-sm">
        <CardHeader>
          <CardTitle className="text-3xl">Login</CardTitle>
          <CardDescription>
            Enter your email below to login to your account
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              placeholder="m@example.com"
              required
              type="email"
            />
          </div>

          <Button className="w-full">Login</Button>
          <Separator />
          <Button className="w-full flex gap-2" variant="outline">
            <Github />
            Login with GitHub
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
